# Generated by Django 5.0.4 on 2024-04-03 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DishModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100, unique=True, verbose_name='Название блюда')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='ReceptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=100, verbose_name='Ингредиент')),
                ('count', models.IntegerField(default=1, verbose_name='Количество')),
                ('measure', models.CharField(choices=[('шт', 'шт'), ('кг', 'кг'), ('л', 'л'), ('мл', 'мл')], default='шт', max_length=2, verbose_name='Единица измерения')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='recept.dishmodel', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
